[tool.ruff]
extend-exclude = ["tests/cases"]
line-length = 120

[tool.ruff.lint]
exclude = ["tests/cases/*"]
select = ["E", "F", "I", "B", "A"]

[tool.ruff.format]
exclude = ["tests/cases/*"]

[tool.mypy]
